version: '2'

services:
  database:
    image: mysql:8.0
    volumes:
      - ./server/database/conf.d:/etc/mysql/mysql.conf.d/
      - ./server/database/data:/var/lib/mysql
      - ./server/database/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'

  redis:
    image: redis

  php:
    build: ./server/php-fpm
    depends_on:
      - database
      - redis
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - app-sync:/var/www/app
    working_dir: /var/www/app

  server:
    build: ./server/nginx
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./server/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server/nginx/log:/var/log/nginx
    ports:
      - 80:80

  composer:
    image: composer:1.4
    volumes_from:
      - php
    working_dir: /var/www/app

volumes:
  app-sync:
    external: true